# Generated by Django 2.2.7 on 2019-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_survey_editable_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='template',
        ),
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner'),
        ),
    ]
